# samples/animations/analysis_options.yaml
# https://github.com/flutter/samples/blob/master/animations/analysis_options.yaml

include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_types_on_closure_parameters: false # コードリーディング時の詳細不明関数式への対応として、関数式のパラメーターにも型を明示させる。
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    # Required because of the numbered sources in  lib/src/basics
    file_names: false
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true