name: extreme widget test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - develop
jobs:
  extreme_widget_test:
    name: flutter extreme widget test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: set up flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.8.0'
      - name: flutter pub get
        run: flutter pub get

      # 全てのエクストリームWidgetテストを実行
      - name: flutter exstreme widget test
        run: flutter test test/